### ISSUE TITLE
Réponse du professeur ( Justification d'une réponse )

### ISSUE THREAD

**Issue by Meehdi** [TSaaP/tsaap-notes#102]
Story 19

En tant qu'étudiant
Je veux que le professeur puisse ajouter sa propre réponse à une question où la justification de la réponse est demandée
De telle sorte que les étudiants auront une réponse correcte et précise au cas où les justifications données par les étudiants ne les sont pas.

**Comment by jfparmentier** [comment]
Je ne comprends pas le rôle : pourquoi en tant que étudiant et pas enseignant ?
Je ne comprends pas ce qui se passe. Veux t-on que les étudiants voient toujours la réponse du prof en plus de la réponse des autres ? Où à la place ? Et à quelle phase ? 3 eme ?
Cela s'oppose d'après moi à l'idée de Tsaap-Notes : une réponse "correcte et précise" d'un point de vue du prof peut être d'aucune utilité pour les étudiants. Sinon pas besoin de faire tsaap-notes, suffit que le prof donne "la bonne" explication.

**Comment by bonenfant** [comment]
The proper goal of TsaapNotes exercices is to offer answers written by student, with student words. If students know that a teacher will provide a "correct and succinct" answer, we change the exercice.

**Comment by FranckSilvestre** [comment]
fixed with issue #196
