### ISSUE TITLE
Unsubscribe to email notifications from an email notification

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#105]
### Description

As a student
I want to unsubscribe to email notifications from an email notification
So that I don't have to delete mails if I don't read them

### Acceptance tests

Given
A user in his mailbox reading the TsaaP-Notes daily notification
When
The user follows the "Unsubscribe all daily notifications from TsaaP-Notes" link
Then
A webpage is shown with a message saying if it worked or why it didn't
And
The user doesn't receive any daily notification from TsaaP-Notes

Given
A user in his mailbox reading the TsaaP-Notes mention notification
When
The user follows the "Unsubscribe all mention notifications from TsaaP-Notes" link
Then
A webpage is shown with a message saying if it worked or why it didn't
And
The user doesn't receive any mention notification from TsaaP-Notes

Given
An user in his mailbox reading the TsaaP-Notes daily or mention notification
When
The user follows the "Manage notifications" link
Then
A webpage is shown to manages TsaaP-Notes subscriptions asking for connection if not logged in

- [x] add a link to settings page in notification mails
- [x] create a link to unsubscribe to daily newsletter
- [x] create a link to unsubscribe to newsletter
- [x] add link to the unsubscribe daily newsletter page in notifications mails
- [x] add link to the unsubscribe mention newsletter page in notifications mails

**Comment by Minizarbi** [comment]
Split key generation and mail generation
Use if possible activation keys
