### ISSUE TITLE
Merge and optimization of response and mention sql request in only one request

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#112]
### Description

Currently, there are 2 different sql queries to notify user on responses or mentions.  
But, a response to a note contains a mention of the user who is answered. As a consequence, it is more efficient to use the same query for both response and mention.
The current mention query has to be modified to no more exclude response and the response query has to be removed from the code.

**Comment by Minizarbi** [comment]
I dropped the database and create it again.
I logged in with fsil account.
I changed the mail to receive notifications.
I logged out to log in with mary account.
I went into science scope.
I added a note "@fsil Hi".
I waited (it can be up to 5 minutes).
I received the notification mail.
