### ISSUE TITLE
Note taking can be disabled on a given scope

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#116]
### Description

As a user owner of a scope
I can choose to disable note taking activity
So that Tsaap-Notes is only used as an audience assesment system (only for interactive questions) for this scope

### Acceptance tests

*Given*
A user authenticated on Tsaap-Notes
*When*
The user create a new scope and completes the creation form
*Then*
The form provides the user with a check box allowing the activation or disactivation of note taking activity
*and* 
This check box is by default not checked, indicating that by default note taking activity will not be enabled
*When*
The user checked the box and save the modification
*Then*
A message indicating that the modification has been saved is displayed on the page

*Given*
A scope created with note taking disabled
*and*
A user authenticated on Tsaap-Notes consulting the page of the given scope
*Then*
The page displays only the content corresponding to the "Questions" tabs
*and*
The two tabs "Notes" and "Questions" are not displayed (they're are unuseful in this configuration)

*Given*
A scope already created with note taken enabled 
*and* 
The user owner of this scope
*When* 
The user edits properties of the scope via the edition form
*Then* 
The form provides the user with a check box allowing the activation or disactivation of note taking activity
*and* 
The check box is checked
*When*
The user unchecked the box and save the modification
*Then*
A message indicating that the modification has been saved is displayed on the page

*Given*
A scope with note taken disabled after some notes have been taken on this scope
*and* 
An authenticated user consulting content of the given scope
*Then* 
All actions consisting on adding a new note on the "Notes" tabs are disabled
*and*
The "Notes" tab labelled is now "Notes (disabled)".

**Comment by FranckSilvestre** [comment]
Just launched tests : 10 integrations tests failed.

**Comment by Minizarbi** [comment]
It is fixed now, we will be more careful to check again the DoD even after rebasing next time.
