### ISSUE TITLE
Students ready to start

### ISSUE THREAD

**Issue by fmigeon** [TSaaP/tsaap-notes#118]
### Description

As a teacher 
I want to know how many students are ready to start questions of a scope
So that I know if students are ready to start (and it avoids me to ask this as a question)

**Comment by jfparmentier** [comment]
what does meand "ready to start" ? They are in  your classroom, so they must be with you, not reading their smartphone. ?

**Comment by fmigeon** [comment]
It means connected to Tsaap-Notes, focused on the current scope, and ready to answer to the questions.
