### ISSUE TITLE
desactivation emails quand une reponse est ajoutee

### ISSUE THREAD

**Issue by jfparmentier** [TSaaP/tsaap-notes#126]
En tant qu'enseignant
je veux pouvoir ne pas recevoir un email a chaque fois qu'un etudiant poste une reponse à une de mes questions
de telle sorte que quand j'ai un cours avec 200 eleves je ne recoive pas 200 emails

**Comment by FranckSilvestre** [comment]
This issue is fixed since we notify only on mentions and note on "responses".
