### ISSUE TITLE
Display the details (Gift code) for a given question

### ISSUE THREAD

**Issue by erikmd** [TSaaP/tsaap-notes#129]
## Description
As a teacher using Tsaap-Notes
I would like to be able to display the Gift code for a given question
In order to easily export it and/or double-check the True/False answers.

**Comment by raclet** [comment]
why only the recently-added?

**Comment by erikmd** [comment]
Indeed, this would be useful for all questions. Reformatted the User Story accordingly.

**Comment by erikmd** [comment]
Closing as duplicate of TSaaP/tsaap-notes#123
