### ISSUE TITLE
Setup of Travis CI for continuous integration

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#134]

**Comment by maelvalais** [comment]
Thanks for that `.travis.yml`, helps me understand the structure of the project! 

I think having `README.md` and `INSTALL.md` would be extremely helpful to newcomers (in the event you seek external contributions).

Maël

**Comment by FranckSilvestre** [comment]
Hi Maël,

Thanks for your message. 
You’re right about the README and INSTALL. I’ll do my best to write them in the next weeks.

If you want to discuss the way you could contribute, we can organize a RDV at the university. I saw you work at UT3 :-).

Franck

**Comment by maelvalais** [comment]
Sure,  I would be honored to be introduced to your project!
