### ISSUE TITLE
Default choice is set when answering for the firts time to N-phases question

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#157]
Default choice is set when answering for the firts time to N-phases question on *Firefox* only.
![capture d ecran 2016-07-13 a 11 35 05](https://cloud.githubusercontent.com/assets/1417089/16798856/53aff9e8-48ee-11e6-922c-8a04b6d9e06d.png)

**Comment by Minizarbi** [comment]
Can't reproduce

**Comment by FranckSilvestre** [comment]
Can't reproduce either.
