### ISSUE TITLE
Choosing 4 evaluator for open-ended questions

### ISSUE THREAD

**Issue by jfparmentier** [TSaaP/tsaap-notes#170]
As a teacher,
I want to choose 4 evaluators by explanation in an open-ended question
in order to increase the number of evaluators by explanation because due to lost of students between phase 1 and phase 2, a lot of explanations have less than 3 evaluators even if I have chosen 3 when I have created the question.

**Comment by jfparmentier** [comment]
I think 5 is also ok. For instance, instead of asking 3 questions and review 3 answers by questions, I can ask 2 questions and review 5 answers. So 10 instead of 9 assessments by student is ok for me.

**Comment by FranckSilvestre** [comment]
This story is estimate with 5 points because it implies modification of the repartition algorithm
