### ISSUE TITLE
Pagination on contexts page fails with filter params

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#27]

**Comment by peletloick** [comment]
I think there is an issue with the filter delimitation, if you use the pagination before the filter it is ok.

https://notes.tsaap.eu/tsaap-notes/scope/index?max=20&filter=__FOLLOWED__  ==> OK
https://notes.tsaap.eu/tsaap-notes/scope/index?filter=__FOLLOWED__&offset=0  ==> NOK

 Tsaap-Notes version 2.3.9
