### ISSUE TITLE
system notification

### ISSUE THREAD

**Issue by arnaud33200** [TSaaP/tsaap-notes#36]
### Description

As a user 
I want to be notified when an answer has been given on one of my note
So that I can get aware early of relevant information to me

### Acceptance test

*Given*
A user "A" having posted 2 notes asking something
*And*
A user "B" who has answered the 2 notes posted by user A
*And*
A user "C" who has answered only one of the 2 notes

*Then*
In the next five minutes, the user A receive an email notification indicating for each note he has received answer(s). The message contain the original note and the answer(s) of each note. The presentation should be inspired by the already used email notification template.

**Comment by FranckSilvestre** [comment]
To test the email notification you have to configure the mail server in an external config file and then launch the application with the VM argument as follows:
-Dtsaap-notes.config.location=/path/to/the/config/file.groovy
To see how to set up the config file for the configuration of the mail server:
https://grails.org/plugin/mail
