### ISSUE TITLE
Add an unsubscribe link at the end of the email notifications

### ISSUE THREAD

**Issue by NitriKx** [TSaaP/tsaap-notes#79]
That would be great that the emails sent regularly to the subscribers of a scope contain a direct link to unsubscribe from the mailing list.

For example :
<img width="1203" alt="capture d ecran 2015-11-06 14 45 03" src="https://cloud.githubusercontent.com/assets/1231438/10998374/fffda340-8494-11e5-84bd-508f51afe574.png">

**Comment by Minizarbi** [comment]
I sawn an Unsubscribe Tsaap-Notes button on the account configuration on TsaaP Notes, but I have no idea what it is doing, when I clicked on it, it just logged me out, and I have to log in and accept the conditions again.
Is there a link between this button and the mail notifications, or is is just a Log out button with the wrong name?

**Comment by FranckSilvestre** [comment]
redundant with #103
