### ISSUE TITLE
Teacher can access bad responses

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#92]
### Description

As a teacher 
I want to consult "bad" explanations
In order to identify students misconception in a deeper way

### Acceptance tests

_Given_
A closed N-phase interactive session 
_and_
The question linked to the interactive session
_and_ 
The owner of the question (called the teacher in the following text) consulting the results of the question

_When_
The teacher clics the button "See all explanations"
_Then_
A popup window displays all explanations sorted by score in descending order  and grouped by response.

### Ergonomic hints

- The interface used to display explanations is an accordion (http://getbootstrap.com/javascript/#collapse-example-accordion).
- The heading of each group is structured as follow:
Response: _response index_ - Score: _score value_ - Response count: _count_ 
- For the group corresponding to the good response (score of 100%), explanations are sorted by mean grade in descending order (as it is currently).  
- For other groups explanations are sorted by username.
![nouveau document 5_1](https://cloud.githubusercontent.com/assets/1417089/16623898/f667d4e8-439f-11e6-9559-ca89fbe5ae80.jpg)

### Warning
This feature is provided only for teacher, i.e. for the owner of the scope (and the question). The current behaviour is kept the same for the students.

**Comment by bonenfant** [comment]
Moreover, as a teacher I would like to have a file containing all answers and ways to sort them (by grades, by name, by delay of answer, by modification between the 2 phases...)

**Comment by FranckSilvestre** [comment]
@bonenfant This feature is already available for a N phases interactive session.

**Comment by FranckSilvestre** [comment]
Accordions bugg when trying to display empty list of explanations (case where some students give an answer without associated explanations).
