### ISSUE TITLE
Teacher can access results of the first submission just after the first phase is closed in an N phases interactive session

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#93]
### Description

As a teacher
I want to access results of the first submission just after the first phase is closed 
So that I can see the responses trend at the end of the first phase 
### Acceptance tests

_Given_ 
An N phases interactive session 
_and_
the owner of the question linked to the interactive session (called "the teacher" in the following text) 
_and_ 
the teacher has launched the first phase of the interactive session
_and_ 
students have answered and are waiting for the end of the first phase

_When_
The teacher closed the first phase
_then_
The chart showing the responses distribution is displayed under a tab labelled "First submission (response count: _count_)"
_and_
below the chart a button labelled "See explanations" is displayed
_and_ 
the button "Start the second phase" is displayed at the right of the "See explanations" button.

![nouveau document 5_2 - copie](https://cloud.githubusercontent.com/assets/1417089/16624267/565b75fc-43a1-11e6-9c76-7ce90c7b6837.jpg)

_When_
The teacher clics on the "See explanations" button
_then_
A popup window appears and displays all explanations (in an accordion, see #92)
### Warning

Only the teacher is provided with this feature !

**Comment by jfparmentier** [comment]
En tant que prof
je peux decider de ne pas faire la suite des phases (>=2)
de telle sorte que si 90% des étudiants ont juste alors je ne fasse pas les autres phases (gains de temps)
