### ISSUE TITLE
Answer explanation can be provided as formatted text

### ISSUE THREAD

**Issue by FranckSilvestre** [TSaaP/tsaap-notes#94]
### Description
As a user answering a question using  a text field to provide an explanation
I want to use a WYSIWYG editor to type my explanation
So that I can format my answer as I wan't.

### Technical hint
The WYSIWYG editor to integrate **must be**  [ckeditor](http://ckeditor.com/).
The plugin [PBCKCode](http://ckeditor.com/addon/pbckcode) **must be** used to format source code.

**Comment by raclet** [comment]
Interoperability with TouIST ( https://github.com/touist/touist ) used in S2 UE "Logique 1". The input language of TouIST allows to write logical formulas.

**Comment by bonenfant** [comment]
This US is confusing. I'd like to allow student to answer formatted code, but not necessarily "test"/evaluate the code.

**Comment by oGasquet** [comment]
@ bonenfant : more generally, i'd like to allow student to provide answers that are formatted text.
