### ISSUE TITLE
Add feedback during the 3rd phase

### ISSUE THREAD

**Issue by erikmd** [TSaaP/tsaap-notes#96]
## Description
As a teacher using Tsaap-Notes,
When I start the third phase of some N-phase session,
I would like to have some numeric feedback related to the number of submitted (student) evaluations
In order to know at which time it is OK to stop the session.

## Acceptance tests
Trivial

- [x] add or modify function in domain to count responses
- [x] modify the view to add responses counter and refresh button

**Comment by Minizarbi** [comment]
Like phases 1 and 2, but for the third phase
